version: 2
jobs:
  deploy:
    docker:
      - image: python:3.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install poetry
          command: |
            pip install poetry==0.12.16 twine
      - run:
          name: bump porto_alegre_client minor version, build and publish to geru-pypi
          command: |
            make publish
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master